// <copyright file="AutoGeneratedIPlanGridApi.cs" company="PlanGrid, Inc.">
//     Copyright (c) 2016 PlanGrid, Inc. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using Refit;

namespace PlanGrid.Api
{
    public partial class AutoGeneratedIPlanGridApi
    {
        public string ApiKey { get; private set; }
        public RefitSettings Settings { get; private set; }

        public void Initialize(string apiKey, RefitSettings settings)
        {
            ApiKey = apiKey;
            Settings = settings;

            foreach (KeyValuePair<string, Func<HttpClient, object[], object>> methodImpl in methodImpls.ToArray())
            {
                methodImpls[methodImpl.Key] = (client, arguments) => methodImpl.Value(client, FixArguments(arguments));
            }
        }

        private object[] FixArguments(object[] arguments)
        {
            for (int i = 0; i < arguments.Length; i++)
            {
                if (arguments[i] is bool)
                {
                    arguments[i] = (bool)arguments[i] ? "true" : "false";
                }
            }
            return arguments;
        }

        public void Dispose()
        {
            Client.Dispose();
        }
    }
}
