// <copyright file="PlanGridClient.cs" company="PlanGrid, Inc.">
//     Copyright (c) 2015 PlanGrid, Inc. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.Net.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Refit;

namespace PlanGrid.Api
{
    public class PlanGridClient
    {
        public static IPlanGridApi Create(string apiKey = null, string baseUrl = null, string version = "v1", int timeout = 60)
        {
            apiKey = apiKey ?? Settings.ApiKey ?? Environment.GetEnvironmentVariable("PLANGRIDAPIKEY");
            if (apiKey == null)
            {
                throw new ArgumentException("An ApiKey is required. Either pass it in to this method, add it to your App.config file, or set the environment variable \"PLANGRIDAPIKEY\".", nameof(apiKey));
            }
            baseUrl = baseUrl ?? Settings.ApiBaseUrl ?? "https://io.plangrid.com";

            string url = $"{baseUrl}/{version}";
            var settings = new RefitSettings
            {
                JsonSerializerSettings = new JsonSerializerSettings
                {
                    DateFormatHandling = DateFormatHandling.IsoDateFormat,
                    Converters = new List<JsonConverter>(new[]
                    {
                        new StringEnumConverter()
                    })
                }
            };
            var api = (AutoGeneratedIPlanGridApi)RestService.For<IPlanGridApi>(
                new HttpClient(new PlanGridHttpHandler(apiKey))
                {
                    BaseAddress = new Uri(url), Timeout = TimeSpan.FromSeconds(timeout)
                }, 
                settings);
            api.Initialize(settings);
            return api;
        }
    }
}