// <copyright file="PlanGridApiExtensions.cs" company="PlanGrid, Inc.">
//     Copyright (c) 2015 PlanGrid, Inc. All rights reserved.
// </copyright>

using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Refit;

namespace PlanGrid.Api
{
    public static class PlanGridApiExtensions
    {
        public static async Task<T> Resolve<T>(this IPlanGridApi api, RecordReference<T> reference)
        {
            var generatedApi = (AutoGeneratedIPlanGridApi)api;
            RefitSettings settings = generatedApi.Settings;
            HttpClient client = generatedApi.Client;

            HttpResponseMessage response = await client.GetAsync(reference.Url);
            response.EnsureSuccessStatusCode();
            string content = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<T>(content, settings.JsonSerializerSettings);
            return result;
        }

        public static async Task<Page<T>> Resolve<T>(this IPlanGridApi api, CollectionReference<T> reference)
        {
            var generatedApi = (AutoGeneratedIPlanGridApi)api;
            RefitSettings settings = generatedApi.Settings;
            HttpClient client = generatedApi.Client;

            HttpResponseMessage response = await client.GetAsync(reference.Url);
            response.EnsureSuccessStatusCode();
            string content = await response.Content.ReadAsStringAsync();
            var result = JsonConvert.DeserializeObject<Page<T>>(content, settings.JsonSerializerSettings);
            return result;
        }
    }
}
